extends Node
class_name GlobalEnums

enum STATES {IDLE, WARPATH, TARGET, FLEE, SKIRMISH}

enum ANIM_STATES {IDLE, MOVING, ATTACKING, DEAD}

enum DAMAGE_TYPE {LIGHT, MEDIUM, HEAVY}

enum ARMOR_TYPE {LIGHT, MEDIUM, HEAVY}
